### ISSUE TITLE
Undefined method `SwapFile' for Chef::Resource:Class broken in 1.0.0

### ISSUE THREAD

**Issue by acoulton** [sous-chefs/swap#38]
### Cookbook version
1.0.0

### Chef-client version
12.18.31 (chef-solo)

### Platform Details
Ubuntu 14.04 on EC2

### Scenario:
An existing recipe that was/is working fine with the 0.3.8 version of the cookbook fails with 1.0.0

### Steps to Reproduce:

```ruby
node.default['swap']['path']    = '/mnt/swap'
node.default['swap']['size']**    = 1024 # Mb
node.default['swap']['persist']** = true

swap_file node['swap']['path'] do
  action  :create
  size    node['swap']['size']
  persist node['swap']['persist'] 
end
```

### Expected Result:
A swap file is created and chef is successful.

### Actual Result:

The run fails with:
```
18:43:22 ================================================================================
18:43:22 Error executing action `create` on resource 'swap_file[/mnt/swap]'
18:43:22 ================================================================================
18:43:22 
18:43:22 NoMethodError
18:43:22 -------------
18:43:22 undefined method `SwapFile' for Chef::Resource:Class
18:43:22 
18:43:22 Cookbook Trace:
18:43:22 ---------------
18:43:22 /var/chef-solo/cache/cookbooks/swap/libraries/swapfile_provider.rb:29:in `load_current_resource'
18:43:22 
18:43:22 Resource Declaration:
18:43:22 ---------------------
18:43:22 # In /var/chef-solo/cache/cookbooks/ingenerator-base/recipes/swap.rb
18:43:22 
18:43:22  23: swap_file node['swap']['path'] do
18:43:22  24:   action  :create
18:43:22  25:   size    node['swap']['size']
18:43:22  26:   persist node['swap']['persist'] 
18:43:22  27: end
18:43:22  28: 
18:43:22 
18:43:22 Compiled Resource:
18:43:22 ------------------
18:43:22 # Declared in /var/chef-solo/cache/cookbooks/ingenerator-base/recipes/swap.rb:23:in `from_file'
18:43:22 
18:43:22 swap_file("/mnt/swap") do
18:43:22   action [:create]
18:43:22   retries 0
18:43:22   retry_delay 2
18:43:22   default_guard_interpreter :default
18:43:22   declared_type :swap_file
18:43:22   cookbook_name "ingenerator-base"
18:43:22   recipe_name "swap"
18:43:22   size 1024
18:43:22   persist true
18:43:22 end
18:43:22 
18:43:22 Platform:
18:43:22 ---------
18:43:22 x86_64-linux
```

**Comment by tas50** [comment]
Fixed in 2.0.

**Comment by acoulton** [comment]
Thanks @tas50
