### ISSUE TITLE
undefined method `SwapFile' for Chef::Resource:Class

### ISSUE THREAD

**Issue by dk8996** [sous-chefs/swap#49]
### Cookbook version
Latest version 2.0.0

### Chef-client version
11.10 

### Platform Details
Ubuntu 14.04 LTS (Opsworks on AWS)

### Scenario:
We are getting the error below, this started happening in the last few days. 

NoMethodError
-------------
undefined method `SwapFile' for Chef::Resource:Class
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/swap/libraries/swapfile_provider.rb:29:in `load_current_resource'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/web/recipes/boxsetup.rb
 
3: swap_file '/mnt/swap' do
4:   size      3072   # MBs
5: end
6:

**Comment by tas50** [comment]
This cookbook requires chef 12.5 or later. You'll need to upgrade your client

**Comment by dk8996** [comment]
What version of swap works with 11.10?

**Comment by tas50** [comment]
0.4
